# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='ENTER CONTENT!'),
        ),
    ]
