# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(default='')),
            ],
            options={
                'ordering': ('book',),
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='link',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='link',
            name='links',
            field=models.ManyToManyField(to='books.Link'),
        ),
    ]
