# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20171201_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
